import 'package:event_run/features/auth/domain/entities/vendor.dart';
import 'package:event_run/features/auth/domain/repositories/auth_repository.dart';

/// Use case for signing up a new user
class SignupUseCase {
  SignupUseCase(this._authRepository);

  final AuthRepository _authRepository;

  /// Execute signup with vendor data and password
  Future<Vendor> execute({
    required String businessName,
    required String fullName,
    required String email,
    required String phone,
    required String password,
  }) async {
    // Validate inputs
    if (businessName.isEmpty ||
        fullName.isEmpty ||
        email.isEmpty ||
        phone.isEmpty ||
        password.isEmpty) {
      throw Exception('All fields are required');
    }

    // Create vendor entity (ID will be generated by backend in real app)
    final vendor = Vendor(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      businessName: businessName,
      fullName: fullName,
      email: email,
      phone: phone,
    );

    // Call repository to signup
    return await _authRepository.signup(vendor, password);
  }
}
